### ISSUE TITLE
this looks cool!

### ISSUE THREAD

**Issue by kellertuer** [olivierverdier/ManifoldNormal.jl#5]
Hi Olivier,
this looks cool!

Should we link to this somewhere from Manifolds maybe (Readme/docs)?

In the long run it would be super great to have something like a ManifoldsDistribution package, see this super old issue at https://github.com/JuliaManifolds/Manifolds.jl/issues/57, just as a remark if you feel that would be something we could start (over on JuliaManifolds).
Similarly if you feel that one of your manifold packages would “live” over there nicely as well, we happily could host them as well; an advantage might be that there is more than one maintainer with rights on the repository – and when you decide, we can surely and would happily of course also add you to the org. I am confident that Mateusz would not have anything against that.

(maybe this is more of a discussion point and not an issue, sorry for that, but the repo does not have discussions activated).

**Comment by olivierverdier** [comment]
Thank you for your comment! I have now activated discussions (I was not aware of that possibility, thanks!). 

I was not aware either of the issue you link to. This repo implements various push-forwards of normal distributions. That corresponds to `Retracted` and `Riemannian` as special cases, but there are others as well (`ActionNoise`, for instance).

I have to apologize for "hijacking" the Manifold namespace for some of my projects. I hope you do not mind too much.

Hosting some of these projects in JuliaManifolds is a great idea.

You can definitely link to this project in the Manifolds documentation, that would be a good start, thank you for suggesting that.

**Comment by kellertuer** [comment]
Hi,

absolutely no worries, it is not easy to have all the issues and ideas in mind that “float around”; just that the “proper randomness” thing is something we have in there for quite a while; I personally usually just need “some random point on M” to start my optimisation at – therefore `rand(M)` is sometimes also just some poor-mans-randomness.
Having that properly worked out would be great.
Push forwards of noises is a very nice group of them definelty.

For the highjacking – no worries either! We do not own the name, quite the opposite, it is great to see more packages!
The idea of having that in JuliaManifolds is really to not be dependent on a single person, it is easier (and by now quite common) to organise packages in Julia in organisations for certain topics.
I can check with Mateusz what we could do here – he will also be at NTNU for the autumn semester (coming here mid September). 

So – no worries, this was really just a point to check whether you would be interested, and great to hear you are!
